### ISSUE TITLE
actix-web v3 rollup

### ISSUE THREAD

**Issue by robjtede** [actix/actix-web#1554]
What is left for a v3 release. Feel free to modify below list. Primarily, I think the memory leak issues need putting to bed one way or the other.

- [x] #1497 rustls integration bug
- [x] #1428 mem leak
- [x] #1523 mem leak
- [x] #1500 mem leak
- [x] #1550 excessive buffer use
- [x] #1556 license violation
- [x] ~actix/actix-net/pull/113~ / actix/actix-net/pull/158 unsoundness in actix-service
- [x] actix/actix-net/pull/161 unsoundness in actix-utils
- [x] actix/actix-net/issues/91 unsounddness in actix-codec
- [x] #1614 unsoundness in actix-http
- [x] #1641 form/json config
- [x] #1634 migrate to new versions of actix-{codec,utils}
- [x] #1642 review and document remaining unsafe blocks
- [x] promote -net packages out of beta
- [x] promote actix v0.10 out of beta

**Comment by zizhengtai** [comment]
May I ask what makes this a major release? I.e., what are the the breaking changes compared to v2?

**Comment by robjtede** [comment]
Breaking changes documented here: https://github.com/actix/actix-web/blob/master/MIGRATION.md. Also the time crate was updated and causes breaking changes to things like setting cookie expiry times.

**Comment by jtescher** [comment]
@robjtede May want to add #1464 as well

**Comment by popzxc** [comment]
Hello everyone. Is it possible to release a new beta version with the memory leaks bug fixed? I want to migrate my project from actix 1.0 to 3.0, but the memory leak issue is the only thing that stops me (other release blockers are not).

**Comment by attila-lin** [comment]
> Hello everyone. Is it possible to release a new beta version with the memory leaks bug fixed? I want to migrate my project from actix 1.0 to 3.0, but the memory leak issue is the only thing that stops me (other release blockers are not).

@JohnTitor   How about releasing a new beta version?

**Comment by JohnTitor** [comment]
@attliaLin Sounds good, will do.

**Comment by ctopher7** [comment]
When is the stable release of v3 coming?

**Comment by JohnTitor** [comment]
We should migrate new versions of actix-{codec,utils}, at least: #1634

**Comment by Silentdoer** [comment]
could release stable v3 currently?
